# Generated by Django 3.1.2 on 2020-10-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201026_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='active',
            field=models.IntegerField(blank=True, choices=[(0, 'Sedentary'), (1, 'Active Person')], null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='alcohol',
            field=models.IntegerField(blank=True, choices=[(0, 'NO'), (1, 'YES')], null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='cardio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='cholesterol',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='glucose',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='smoker',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'YES')], null=True),
        ),
    ]
